export default Images = {
  logo: require('../assets/Images/logo.png'),
  loginImage: require('../assets/Images/loginImage.png'),
  SignupImage: require('../assets/Images/SignupImage.png'),

  eye: require('../assets/Images/eye.png'),
  google: require('../assets/Images/GoogleIcon.png'),
  facebook: require('../assets/Images/FacebookIcon.png'),
  twiter: require('../assets/Images/TwitterLogo.png'),
  refferImage: require('../assets/Images/referIdImage.png'),
  menu: require('../assets/Images/menu.png'),
  sort: require('../assets/Images/sort.png'),
  bell: require('../assets/Images/bell.png'),
  cartTrolly: require('../assets/Images/cartTrolly.png'),
  trollyDark: require('../assets/Images/tollyDark.png'),

  filter: require('../assets/Images/filter.png'),
  search: require('../assets/Images/searchIcon.png'),
  homeLight: require('../assets/Images/homeLight.png'),
  homeDark: require('../assets/Images/homeDark.png'),
  catagoryLight: require('../assets/Images/catagoryLight.png'),
  catagoryDark: require('../assets/Images/catagoryDark.png'),
  storeLight: require('../assets/Images/storeLight.png'),
  storeDark: require('../assets/Images/storeDark.png'),
  userLight: require('../assets/Images/userLight.png'),
  userDark: require('../assets/Images/userDark.png'),

  catIcon: require('../assets/Images/catIcon.png'),
  salesIcon: require('../assets/Images/salesIcon.png'),
  offersIcon: require('../assets/Images/offersIcon.png'),
  groupByIcon: require('../assets/Images/groupByIcon.png'),
  rewardIcon: require('../assets/Images/rewardIcon.png'),
  productSlide1: require('../assets/Images/productSlide1.png'),
  btnIcon: require('../assets/Images/btnIcon.png'),
  whatsapp: require('../assets/Images/whatsapp.png'),
  rightArrow: require('../assets/Images/rightArrow.png'),

  cat1: require('../assets/Images/cat1.png'),
  cat2: require('../assets/Images/cat2.png'),
  cat3: require('../assets/Images/cat3.png'),

  cat3: require('../assets/Images/cat3.png'),
  cat3: require('../assets/Images/cat3.png'),
  share: require('../assets/Images/share.png'),
  buyIcon: require('../assets/Images/buyIcon.png'),
  mobile: require('../assets/Images/mobile.png'),

  backArrow: require('../assets/Images/backArrow.png'),
  product2: require('../assets/Images/product2.png'),
  product3: require('../assets/Images/product3.png'),

  users: require('../assets/Images/users.png'),

  rightLine: require('../assets/Images/rightLine.png'),
  signup: require('../assets/Images/signup.png'),
  earning: require('../assets/Images/earning.png'),
  customize: require('../assets/Images/customize.png'),
  bigSale: require('../assets/Images/bigSale.png'),
  inviteImage: require('../assets/Images/initeImage.png'),
  shareIcon: require('../assets/Images/shareIcon.png'),
  get: require('../assets/Images/get.png'),

  like: require('../assets/Images/like.png'),
  dislike: require('../assets/Images/dislike.png'),

  plus: require('../assets/Images/plus.png'),
  minus: require('../assets/Images/minus.png'),

  trash: require('../assets/Images/trash.png'),
  cartImage: require('../assets/Images/cartImage.png'),
  location: require('../assets/Images/location.png'),
  right: require('../assets/Images/right.png'),
  successful_image :require('../assets/Images/successful-image.png'),
  profileImage:require('../assets/Images/profileImage.png'),
  myAccount: require('../assets/Images/account.png'),
  groupBuy:require('../assets/Images/groupBuy.png'),
  sharedProduct:require('../assets/Images/shareProduct.png'),
  myStore: require('../assets/Images/myStore.png'),
  myOrder:require('../assets/Images/myOrder.png'),
  refAndEarn:require('../assets/Images/referAndEarn.png'),
  termsAndCondition:require('../assets/Images/termsAndCondition.png'),
  privacyPolicy:require('../assets/Images/privacyPolicy.png'),
  howWorks: require('../assets/Images/howWorks.png'),
  faq: require('../assets/Images/faq.png'),
rateApp:require('../assets/Images/rateApp.png'),
logout:require('../assets/Images/logout.png'),
howItWorks:require('../assets/Images/howWorks-img.png'),
heading1:require('../assets/Images/heading1.png'),
heading2:require('../assets/Images/heading2.png'),
heading3:require('../assets/Images/heading3.png'),




};
